GET http://localhost:3000/api/pokemonTypes

###
GET http://localhost:3000/api/pokemon

###
GET http://localhost:3000/api/pokemon/db

###
GET http://localhost:3000/api/pokemon/db/1025

###
GET http://localhost:3000/dbConnection/sync

###
GET http://localhost:3000/dbConnection/drop

###
DELETE http://localhost:3000/api/pokemon/deleteDexNum/5
